### PR TITLE
[SKYR-871] Rename all from Mocker to Worker

### PR DESCRIPTION
**Pull request by texmachina**

### CODE REVIEW

**Comment by sacheth003** [comment]
@texmachina So for design partners that have already been playing around with this helm chart. Will their workflow already exist for older versions? For example, can they still run `helm install ... skyramp/mocker`, given they are okay using v0.4.17 (or whatever the last version was)?

**Comment by texmachina** [comment]
@sacheth003 -- there is no way that I know of to let them be able to continue to use the mocker chart since it's now the worker chart. They'll ideally need to remove the mocker chart and install the worker chart. We can leave the locker chart in the index for a while though if it makes sense.

**Comment by sacheth003** [comment]
Got it. No issues either way, just wondering.

**Comment by texmachina** [comment]
All good! Yeah it would be nice to prevent disruption, but at least we don't have too many using it yet!

**Pull request merged**
